version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  tradingapp:
    build:
      context: .
    environment:
      - ConnectionStrings__Default: "Server=sqlserver;Database=TradingAppDb;User Id=sa;Password=${SA_PASSWORD}"
      - Email__Host: ${SMTP_SERVER}
      - Email__Port: ${SMTP_PORT}
      - Email__Username: ${SMTP_USER}
      - EmailSettings__SmtpPass: ${SMTP_PASS}
      - FinanceApi__BaseUrl: ${FINANCE_API_URL}
      - Email__From : kstvkmrchanda2@gmail.com
      - Email__To: kstvkmrchanda2@gmail.com
    depends_on:
      - sqlserver
    ports:
      - "8080:80"

  pythonservice:
    build:
      context: ./server
    environment:
      PYTHON_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
